### ISSUE TITLE
Unable to find config file.

### ISSUE THREAD

**Issue by MiqueiasMaia** [alexpechkarev/google-maps#69]
I'm trying to execute the following lines to get the Place ID from Google.

```
public function findGoogleId($placeName, $city, $state, $country)
    {
        $response = \GoogleMaps::load('geocoding')->setParam([
            "name" => $placeName,
            "address" => $city . " " . $state . " " . $country,
        ])->get();

        return $response->id;
    }
```
I'm getting this following error:

`> ErrorException: Unable to find config file. in file {path}\vendor\alexpechkarev\google-maps\src\WebService.php on line 254`

My stacktrace it's:

```
#0 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\alexpechkarev\google-maps\src\WebService.php(220): GoogleMaps\WebService->validateConfig('geocoding')
#1 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\alexpechkarev\google-maps\src\GoogleMaps.php(33): GoogleMaps\WebService->build('geocoding')
#2 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(239): GoogleMaps\GoogleMaps->load('geocoding')
#3 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\app\Util\Google.php(14): Illuminate\Support\Facades\Facade::__callStatic('load', Array)
#4 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\app\Http\Controllers\API\PlaceController.php(171): App\Util\Google->findGoogleId('Ryori Sushi Lou...', 'Fortaleza', 'CE', 'Brasil')
#5 [internal function]: App\Http\Controllers\API\PlaceController->getAndSetGoogleID()
#6 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#7 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('getAndSetGoogle...', Array)
#8 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\API\PlaceController), 'getAndSetGoogle...')
#9 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController()
#10 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(680): Illuminate\Routing\Route->run()
#11 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\app\Http\Middleware\Cors.php(32): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\Cors->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\barryvdh\laravel-cors\src\HandleCors.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 60, '1')
#20 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#24 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Routing\Router.php(612): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#27 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\barryvdh\laravel-cors\src\HandleCors.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\app\Http\Middleware\Cors.php(32): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\Cors->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#44 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#45 C:\lamp\htdocs\workspace\appi9\foodselfieAPI\server.php(21): require_once('C:\\lamp\\htdocs\\...')
#46 {main}
```

How can I solve it?

**Comment by MiqueiasMaia** [comment]
This error it's happening in
```
if (!Config::has('googlemaps')) {
     throw new ErrorException('Unable to find config file.');
}
```

in WebService.php.

**Comment by MiqueiasMaia** [comment]
To give a help for others with this same issue, I solved this with
`php artisan config:clear`
